version: '2'
services:
  splunk:
    hostname: splunk-app-for-jenkins
    image: fengxx/splunk-app-for-jenkins
    environment:
      SPLUNK_START_ARGS: --accept-license
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
  jenkins:
    image: fengxx/jenkins-1x
    #image: fengxx/jenkins-2x
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - "splunk"
