version: '2'
services:
  splunk:
    build: splunk
    hostname: splunk-app-for-jenkins
    environment:
      SPLUNK_START_ARGS: --accept-license
    ports:
      - "18000:8000"
      - "18088:8088"
  jenkins:
    build: jenkins-1x
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - "splunk"
